// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chord.proto

package chord

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindHostRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindHostRequest) Reset()         { *m = FindHostRequest{} }
func (m *FindHostRequest) String() string { return proto.CompactTextString(m) }
func (*FindHostRequest) ProtoMessage()    {}
func (*FindHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{0}
}

func (m *FindHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindHostRequest.Unmarshal(m, b)
}
func (m *FindHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindHostRequest.Marshal(b, m, deterministic)
}
func (m *FindHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindHostRequest.Merge(m, src)
}
func (m *FindHostRequest) XXX_Size() int {
	return xxx_messageInfo_FindHostRequest.Size(m)
}
func (m *FindHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindHostRequest proto.InternalMessageInfo

func (m *FindHostRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type FindRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{1}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type Node struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{2}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func init() {
	proto.RegisterType((*FindHostRequest)(nil), "chord.FindHostRequest")
	proto.RegisterType((*FindRequest)(nil), "chord.FindRequest")
	proto.RegisterType((*Node)(nil), "chord.Node")
}

func init() {
	proto.RegisterFile("chord.proto", fileDescriptor_541dae51990542ec)
}

var fileDescriptor_541dae51990542ec = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4b, 0x02, 0x41,
	0x14, 0xc6, 0xd5, 0x4c, 0xf0, 0xad, 0x54, 0x4c, 0x11, 0xb2, 0x11, 0xc8, 0x76, 0xe9, 0xb4, 0x03,
	0x1a, 0x91, 0x87, 0x2e, 0x4a, 0xd1, 0x21, 0x44, 0xb4, 0x53, 0x37, 0x77, 0xe6, 0xb9, 0x3b, 0xa4,
	0x3e, 0x9b, 0x99, 0x0d, 0xf6, 0x8f, 0xed, 0x7f, 0x89, 0x99, 0xd5, 0x10, 0x21, 0xaa, 0xdb, 0x9b,
	0xf9, 0xbe, 0xdf, 0x9b, 0xef, 0x1b, 0x08, 0x44, 0x46, 0x5a, 0xc6, 0x6b, 0x4d, 0x96, 0xd8, 0xa1,
	0x3f, 0x84, 0x17, 0x29, 0x51, 0xba, 0x40, 0xee, 0x2f, 0x93, 0x7c, 0xce, 0x71, 0xb9, 0xb6, 0x45,
	0xe9, 0x89, 0xae, 0xe0, 0xf8, 0x51, 0xad, 0xe4, 0x13, 0x19, 0x3b, 0xc1, 0xf7, 0x1c, 0x8d, 0x65,
	0x27, 0x70, 0xf0, 0x86, 0x45, 0xbb, 0xda, 0xa9, 0x5e, 0x37, 0x27, 0x6e, 0x8c, 0x2e, 0x21, 0x70,
	0xa6, 0xad, 0xe1, 0x08, 0x6a, 0x4a, 0x7a, 0xbd, 0x35, 0xa9, 0x29, 0x19, 0x85, 0x50, 0x1f, 0x91,
	0x44, 0xc6, 0xa0, 0x9e, 0x91, 0xb1, 0x1b, 0xd2, 0xcf, 0xdd, 0xcf, 0x1a, 0xb4, 0x86, 0x2e, 0xc6,
	0x14, 0xf5, 0x87, 0x12, 0xc8, 0xba, 0xd0, 0x9c, 0xe6, 0x42, 0xa0, 0x31, 0xa4, 0xd9, 0x79, 0x5c,
	0x66, 0x8b, 0xb7, 0xd9, 0xe2, 0x07, 0x97, 0x2d, 0x0c, 0xe2, 0xb2, 0x87, 0x5b, 0x1b, 0x55, 0xd8,
	0x0d, 0x04, 0x63, 0x8d, 0x12, 0xff, 0x47, 0xf5, 0xe1, 0xcc, 0xa5, 0xfe, 0x7e, 0x6d, 0x50, 0xbc,
	0xcc, 0x92, 0x05, 0x32, 0xb6, 0xb1, 0xed, 0x54, 0xda, 0x47, 0xef, 0xe0, 0x74, 0x0f, 0x7d, 0x56,
	0xc6, 0xfe, 0x85, 0xbc, 0x87, 0xb6, 0x53, 0x87, 0x0b, 0x32, 0x68, 0xec, 0x58, 0xa3, 0x40, 0xa9,
	0x56, 0x69, 0xf9, 0x3f, 0xbf, 0xe3, 0x1c, 0x1a, 0x23, 0xb2, 0x6a, 0x5e, 0xb0, 0x5d, 0x21, 0xfc,
	0xa1, 0x71, 0x54, 0x19, 0x44, 0xaf, 0x9d, 0x54, 0xd9, 0x2c, 0x4f, 0x62, 0x41, 0x4b, 0x6e, 0x67,
	0xca, 0x64, 0x74, 0xdb, 0xeb, 0xf5, 0x79, 0x4a, 0x5a, 0x72, 0xbf, 0x22, 0x69, 0x78, 0xaa, 0xf7,
	0x15, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xb6, 0xa2, 0x7c, 0x1d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChordServiceClient is the client API for ChordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChordServiceClient interface {
	Successor(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Node, error)
	Predecessor(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Node, error)
	FindSuccessorByTable(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*Node, error)
	FindSuccessorByList(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*Node, error)
	FindClosestPrecedingNode(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*Node, error)
	Notify(ctx context.Context, in *Node, opts ...grpc.CallOption) (*empty.Empty, error)
}

type chordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChordServiceClient(cc grpc.ClientConnInterface) ChordServiceClient {
	return &chordServiceClient{cc}
}

func (c *chordServiceClient) Successor(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/chord.ChordService/Successor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordServiceClient) Predecessor(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/chord.ChordService/Predecessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordServiceClient) FindSuccessorByTable(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/chord.ChordService/FindSuccessorByTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordServiceClient) FindSuccessorByList(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/chord.ChordService/FindSuccessorByList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordServiceClient) FindClosestPrecedingNode(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/chord.ChordService/FindClosestPrecedingNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordServiceClient) Notify(ctx context.Context, in *Node, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/chord.ChordService/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChordServiceServer is the server API for ChordService service.
type ChordServiceServer interface {
	Successor(context.Context, *empty.Empty) (*Node, error)
	Predecessor(context.Context, *empty.Empty) (*Node, error)
	FindSuccessorByTable(context.Context, *FindRequest) (*Node, error)
	FindSuccessorByList(context.Context, *FindRequest) (*Node, error)
	FindClosestPrecedingNode(context.Context, *FindRequest) (*Node, error)
	Notify(context.Context, *Node) (*empty.Empty, error)
}

// UnimplementedChordServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChordServiceServer struct {
}

func (*UnimplementedChordServiceServer) Successor(ctx context.Context, req *empty.Empty) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Successor not implemented")
}
func (*UnimplementedChordServiceServer) Predecessor(ctx context.Context, req *empty.Empty) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predecessor not implemented")
}
func (*UnimplementedChordServiceServer) FindSuccessorByTable(ctx context.Context, req *FindRequest) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSuccessorByTable not implemented")
}
func (*UnimplementedChordServiceServer) FindSuccessorByList(ctx context.Context, req *FindRequest) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSuccessorByList not implemented")
}
func (*UnimplementedChordServiceServer) FindClosestPrecedingNode(ctx context.Context, req *FindRequest) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindClosestPrecedingNode not implemented")
}
func (*UnimplementedChordServiceServer) Notify(ctx context.Context, req *Node) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}

func RegisterChordServiceServer(s *grpc.Server, srv ChordServiceServer) {
	s.RegisterService(&_ChordService_serviceDesc, srv)
}

func _ChordService_Successor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServiceServer).Successor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.ChordService/Successor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServiceServer).Successor(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChordService_Predecessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServiceServer).Predecessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.ChordService/Predecessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServiceServer).Predecessor(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChordService_FindSuccessorByTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServiceServer).FindSuccessorByTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.ChordService/FindSuccessorByTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServiceServer).FindSuccessorByTable(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChordService_FindSuccessorByList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServiceServer).FindSuccessorByList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.ChordService/FindSuccessorByList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServiceServer).FindSuccessorByList(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChordService_FindClosestPrecedingNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServiceServer).FindClosestPrecedingNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.ChordService/FindClosestPrecedingNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServiceServer).FindClosestPrecedingNode(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChordService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chord.ChordService/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServiceServer).Notify(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChordService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chord.ChordService",
	HandlerType: (*ChordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Successor",
			Handler:    _ChordService_Successor_Handler,
		},
		{
			MethodName: "Predecessor",
			Handler:    _ChordService_Predecessor_Handler,
		},
		{
			MethodName: "FindSuccessorByTable",
			Handler:    _ChordService_FindSuccessorByTable_Handler,
		},
		{
			MethodName: "FindSuccessorByList",
			Handler:    _ChordService_FindSuccessorByList_Handler,
		},
		{
			MethodName: "FindClosestPrecedingNode",
			Handler:    _ChordService_FindClosestPrecedingNode_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _ChordService_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chord.proto",
}
